version: '2'

networks:
  web:
    external: true

services:
    # whoowesme-web:
    #   image: traefik:1.5.2-alpine
    #   container_name: whoowesme-web-traefik
    #   restart: always
    #   networks:
    #     - web
    #   ports:
    #     - 80:80
    #     - 8080:8080
    #   links:
    #     - whoowesme-frontend
    #   depends_on:
    #     - whoowesme-frontend
    #   volumes:
    #     - /var/run/docker.sock:/var/run/docker.sock
    #     - ./.docker/traefik/traefik.dev.toml:/traefik.toml
    #   command: --web --docker --docker.domain=whoowesme.local

    whoowesme-frontend:
      build:  
        context: "."
        dockerfile: "./.docker/frontend/Dockerfile"
      container_name: whoowesme-frontend
      restart: always
      volumes:
        - ./frontend:/app
        - /app/node_modules
      environment:
        - REACT_APP_API_BASEURI=http://localhost:8000
        - REACT_APP_ENV=development
      ports:
        - 3000
      logging:
        driver: "none"
      labels:
        - "traefik.docker.network=web"
        - "traefik.frontend.rule=Host:frontend.whoowesme.local"
        - "traefik.port=3000"
        - "traefik.enable=true"
        - "traefik.default.protocol=http"
      networks:
        web:
          aliases:
            - frontend.whoowesme.local
      command: npm install
      command: npm run start
      tty: true

