[build]
  base = 'frontend'
  publish = 'build'
  command = 'npm run build'

[context.production]
  base = 'frontend'
  publish = 'build'
  command = 'npm run build'
  environment = { NODE_VERSION = 'v12.14.0' }

[context.develop]
  base = 'frontend'
  publish = 'build'
  command = 'npm run build'
  environment = { NODE_VERSION = 'v12.14.0' }

[context.netlify-deploy]
  base = 'frontend'
  publish = 'build'
  command = 'npm run build'
  environment = { NODE_VERSION = 'v12.14.0' }

[[redirects]]
  from = '/*'
  to = "/index.html"
  status = 200
  headers = { X-From = "Netlify" }
